# Actions file for CI/CD
name: Django CI Workflow

# triggers for our workflow
on:
  push:
    branches:
      - main
  pull_request:


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version }}

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Cache Pipenv virtualenv
        uses: actions/cache@v2
        id: pipenv-cache
        with:
          path: ~/.local/share/virtualenvs/
          key: ${{ runner.os }}-pipenv-v2-{{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-v2-

      - name: Install dependencies
        env:
          PIPENV_NOSPIN: 'true'
          WORKON_HOME: ~/.local/share/virtualenvs
          PIPENV_CACHE_DIR: ~/.local/share/pipcache
        run: |
          pipenv install --deploy --dev

      - name: Execute the tests
        run: |
          pipenv run python manage.py test
        env:
          DJANGO_SETTINGS_MODULE: jabme.app.settings.prod

      - name: QA Tests
        run: |
          pipenv run pre-commit run -a
